spring.application.name=fooddeliveryapi

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/fooddelivery
# AWS S3
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketname=foodies-onlinefoods

# JWT
JWT_SECRET=yourVeryStrongSecretKeyForJWT123456789
jwt.secret.key=ThisIsMyVerySecretJWTKey12345678901234567890

# Razorpay
razorpay_id=${RAZORPAY_ID}
razorpay_secret=${RAZORPAY_SECRET}

server.port=${PORT:8080}
